### ISSUE TITLE
BaseComponent/MainLayout [Optimization]

### ISSUE THREAD

**Issue by db2k** [flyntwp/flynt-starter-theme#70]
# Todo
* [x] Add `role="document"` to body tag
* [x] Remove MainHeader area
* [x] Implement Touch Icons and important Meta tags for all devices and operation systems
* [x] Check HTML5 Validation
* [x] Check what meta-tags and meta informations we could add to the backend configuration (favicon, touchicons, chrome colortheme hexcode etc.)
* [x] Check if BaseStyles should be moved into a seperate folder
  * **Explanation**: If you have two MainTemplates with the same style, but only the buttons are different for example, you would have  to copy the whole BaseStyle folder into the MainLayout2 module just to have the same basestyle.
* [x] Add Title Tag

*******

# Related Tickets
* [x] #65
* [x] #62

*******

# Related Pull Requests
* #91
